//Copyright 2013 Mobvoi Inc. All Rights Reserved.
package com.mobvoi.streaming.location;

import com.mobvoi.streaming.util.StringUtil;

/**
 * Location, it generated by onebox input
 *
 * @author Jimmy Chen, <ggm19890303@live.cn>
 */
public class Location {
  public static final String COUNTRY = "country";
  public static final String PROVINCE = "province";
  public static final String CITY = "city";
  public static final String SUBLOCALITY = "sublocality";
  public static final String STREET = "street";
  public static final String STREET_NUMBER = "streetNumber";
  public static final String LAT = "lat";
  public static final String LNG = "lng";
  
  private String country = StringUtil.EMPTY_STRING;
  private String province = StringUtil.EMPTY_STRING;
  private String city = StringUtil.EMPTY_STRING;
  private String sublocality = StringUtil.EMPTY_STRING;
  private String street = StringUtil.EMPTY_STRING;
  private String streetNumber = StringUtil.EMPTY_STRING;
  private GeoPoint geoPoint = new GeoPoint();

  public String getCountry() {
    return country;
  }

  public void setCountry(String country) {
    this.country = country;
  }

  public String getProvince() {
    return province;
  }

  public void setProvince(String province) {
    this.province = province;
  }

  public String getCity() {
    return city;
  }

  public void setCity(String city) {
    this.city = city;
  }

  public String getSublocality() {
    return sublocality;
  }

  public void setSublocality(String sublocality) {
    this.sublocality = sublocality;
  }

  public String getStreet() {
    return street;
  }

  public void setStreet(String street) {
    this.street = street;
  }

  public String getStreetNumber() {
    return streetNumber;
  }

  public void setStreetNumber(String streetNumber) {
    this.streetNumber = streetNumber;
  }

  public GeoPoint getGeoPoint() {
    return geoPoint;
  }

  public void setGeoPoint(GeoPoint geoPoint) {
    this.geoPoint = geoPoint;
  }
  
  public String getAddress(){
    StringBuffer buffer = new StringBuffer();
    if(StringUtil.notNullOrEmpty(country)){
      buffer.append(country);
    } else {
      return buffer.toString();
    }
    
    
    if(StringUtil.notNullOrEmpty(province)){
      buffer.append(province);
    }else {
      return buffer.toString();
    }
    
    if(StringUtil.notNullOrEmpty(city)){
      buffer.append(city);
    }else {
      return buffer.toString();
    }
    
    if(StringUtil.notNullOrEmpty(sublocality)){
      buffer.append(sublocality);
    }else {
      return buffer.toString();
    }
    
    if(StringUtil.notNullOrEmpty(street)){
      buffer.append(street);
    }else {
      return buffer.toString();
    }
    
    if(StringUtil.notNullOrEmpty(streetNumber)){
      buffer.append(streetNumber);
    }else {
      return buffer.toString();
    }
    
    return buffer.toString();
  }
  
  public String getFormAddress() {
    StringBuffer buffer = new StringBuffer();
    buffer.append(country);
    buffer.append(",");
    buffer.append(province);
    buffer.append(",");
    buffer.append(city);
    buffer.append(",");
    buffer.append(sublocality);
    buffer.append(",");
    buffer.append(street);
    buffer.append(",");
    buffer.append(streetNumber);
    buffer.append(",");
    buffer.append(geoPoint.getLat());
    buffer.append(",");
    buffer.append(geoPoint.getLng());
    return buffer.toString();
  }
}
